### ISSUE TITLE
Build time scanning does not terminate in timely fashion

### ISSUE THREAD

**Issue by johnou** [classgraph/classgraph#221]
```java
public class BuildTimeScan {

    private static final Logger logger = LoggerFactory.getLogger(BuildTimeScan.class);

    private static final String OUTPUT_FILENAME = "scanresult.json";

    public static void main(String[] args) throws Exception {
        if (args.length != 1) {
            throw new RuntimeException("Output directory not specified");
        }
        String dir = args[0];
        File jsonFile = new File(dir, OUTPUT_FILENAME);

        final Map<Class<?>, Class<?>> concreteImplementations = new ConcurrentHashMap<>();
        ScanResult scanResult = new ClassGraph()
                .whitelistPackages("com.sulake.h4k", "cloud.orbit")
                .enableClassInfo()
                .verbose()
                .scan(ForkJoinPool.commonPool(), 6);

        List<Class<?>> clazzImplementations = new ArrayList<>();

        scanResult.getClassesImplementing(Actor.class.getName()).forEach(classInfo -> {
            if (classInfo.isInterface() || classInfo.isAbstract()) {
                return;
            }
            clazzImplementations.add(classInfo.loadClass());
        });

        logger.info("done scanning..");

        for (Class<?> clazzImplementation : clazzImplementations) {
            Class<?>[] implementationInterfaces = clazzImplementation.getInterfaces();
            if (implementationInterfaces.length == 0) {
                continue;
            }
            for (Class<?> implementationInterface : implementationInterfaces) {
                if (implementationInterface == Remindable.class) {
                    continue;
                }
                if (Actor.class.isAssignableFrom(implementationInterface)) {
                    Class<?> old = concreteImplementations.put(implementationInterface, clazzImplementation);
                    if (old != null) {
                        logger.warn("Multiple actor implementations found for " + implementationInterface);
                    }
                }
            }
        }

        try (PrintWriter writer = new PrintWriter(jsonFile)) {

            writer.print("hi");
        }
    }
}
```

```xml
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>1.6.0</version>
                <executions>
                    <execution>
                        <phase>process-classes</phase>
                        <goals>
                            <goal>java</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <mainClass>BuildTimeScan</mainClass>
                    <commandlineArgs>
                        ${project.build.outputDirectory}
                    </commandlineArgs>
                    <addResourcesToClasspath>true</addResourcesToClasspath>
                </configuration>
            </plugin>
```

```
2018-07-30T11:24:08.429+0200	ClassGraph	Building class graph (took 0.008887 sec)
2018-07-30T11:24:08.442+0200	ClassGraph	Completed scan (took 0.298226 sec)
2018-07-30T11:24:08,870 INFO  [com.sulake.h4k.common.buildtools.BuildTimeScan.main()] (com.sulake.h4k.common.buildtools.BuildTimeScan) done scanning.. []
[WARNING] thread Thread[Log4j2-TF-2-Scheduled-1,5,com.sulake.h4k.common.buildtools.BuildTimeScan] was interrupted but is still alive after waiting at least 15000msecs
[WARNING] thread Thread[Log4j2-TF-2-Scheduled-1,5,com.sulake.h4k.common.buildtools.BuildTimeScan] will linger despite being asked to die via interruption
[WARNING] thread Thread[ForkJoinPool.commonPool-worker-2,5,com.sulake.h4k.common.buildtools.BuildTimeScan] will linger despite being asked to die via interruption
[WARNING] thread Thread[ForkJoinPool.commonPool-worker-5,5,com.sulake.h4k.common.buildtools.BuildTimeScan] will linger despite being asked to die via interruption
[WARNING] thread Thread[ForkJoinPool.commonPool-worker-6,5,com.sulake.h4k.common.buildtools.BuildTimeScan] will linger despite being asked to die via interruption
[WARNING] thread Thread[ForkJoinPool.commonPool-worker-7,5,com.sulake.h4k.common.buildtools.BuildTimeScan] will linger despite being asked to die via interruption
[WARNING] NOTE: 5 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=com.sulake.h4k.common.buildtools.BuildTimeScan,maxpri=10]
java.lang.IllegalThreadStateException
	at java.lang.ThreadGroup.destroy(ThreadGroup.java:778)
	at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:321)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.executeForkedExecutions(MojoExecutor.java:352)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:197)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
```

**Comment by johnou** [comment]
```
[WARNING] thread Thread[Log4j2-TF-2-Scheduled-1,5,com.sulake.h4k.common.buildtools.BuildTimeScan] was interrupted but is still alive after waiting at least 15000msecs
[WARNING] thread Thread[Log4j2-TF-2-Scheduled-1,5,com.sulake.h4k.common.buildtools.BuildTimeScan] will linger despite being asked to die via interruption
[WARNING] NOTE: 1 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=com.sulake.h4k.common.buildtools.BuildTimeScan,maxpri=10]
java.lang.IllegalThreadStateException
	at java.lang.ThreadGroup.destroy(ThreadGroup.java:778)
	at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:321)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
```

here's the stacktrace using scan().

**Comment by lukehutch** [comment]
Interesting. I can replicate this with `.scan(ForkJoinPool.commonPool(), 6)` but not with `.scan()`. I have never tried this with `ForkJoinPool` before, and I'm wondering if some of the semantics are different for that pool type. I am also wondering why you can replicate this with `.scan()` but I can't.

**Comment by lukehutch** [comment]
What JVM version are you running on?

**Comment by lukehutch** [comment]
By the way, with the new API, you can do:

```java
List<Class<?>> clazzImplementations = 
    scanResult.getClassesImplementing(Actor.class.getName())
        .filter(classInfo -> classInfo.isInterface() || classInfo.isAbstract())
        .loadClasses();
```

**Comment by lukehutch** [comment]
Adding `-Dexec.cleanupDaemonThreads=false` solves the problem. I found this here, without explanation:

https://github.com/camelinaction/camelinaction2/issues/52

**Comment by lukehutch** [comment]
It looks like that is indeed the solution, and you can specify it as an option in the `pom.xml` file:

https://stackoverflow.com/a/25166013/3950982

My understanding of this is that the once you start using the `ForkJoinPool.commonPool()`, it must start the threads (lazily) and set them to daemon mode. You actually can't call `ForkJoinPool.commonPool().shutdown()`, the JavaDoc says this is ignored. So what happens is that Maven sees the daemon threads still running after `BuildTimeScan.main(args)` exits. It must be calling `main` as a function, rather than starting it as a subprocess.

I will update the build-time scanning doc. Please let me know if this fixes it for you too.

However, I am still interested to understand how this was happening for you with `.scan()`. The one thread that was still pegged, in the last stacktrace you provided, was created in your code, not by ClassGraph, based on the thread name -- and the thread, once created, was set to daemon mode, and was not shut down before `main` exited. Can you see how that thread might be being created?

**Comment by lukehutch** [comment]
Updated the doc page:

https://github.com/classgraph/classgraph/wiki/Build-Time-Scanning

This fixes it for me.

**Comment by johnou** [comment]
@lukehutch if I remove the slf4j logger it doesn't hang anymore.. so I think we can close this, might be worth putting a note on the Build Time Scanning page though.

**Comment by johnou** [comment]
I know for a fact log4j starts up some threads, could be related.

**Comment by johnou** [comment]
After playing around with it more it seems any "complex" build time scanning implementation will need to be configured with cleanupDaemonThreads set to false or it will hang, thanks for the quick response!

**Comment by lukehutch** [comment]
Thanks for the report, I learned something new, and I'm glad you caught this! I put a note on that page, in the form of an XML comment with links, and the XML example now has the correct configuration tag in it.

**Comment by johnou** [comment]
I have been meaning to implement build time scanning for some time now, the issue we have is that our staging server has the specs of a calculator.. and concurrently starting multiple JVMs on a large classpath kills the box as all processes contend for disk io.

**Comment by johnou** [comment]
I would rather not introduce a specific config for that between environments, it's relatively ok in production but slows down development - the build time scanning is working fine so I think it's a win :+1:

**Comment by lukehutch** [comment]
Great, glad to hear it! If you needed to, you could probably find a way to detect the runtime environment (based on the filesystem structure or something), and set the number of threads only in your staging server.

I forget sometimes that people still have to run on old hardware. Old hardware drives me nuts, so I invest a lot in keeping at the bleeding edge. So it's good to hear reports like this, as a reality check, and to make sure ClassGraph runs OK everywhere.

I did push an update a couple of days ago that calculates the number of threads based on the number of processors:

https://github.com/classgraph/classgraph/blob/master/src/main/java/io/github/classgraph/ClassGraph.java#L62

for a 2-processor system, this formula will translate to allocating 4 threads.

**Comment by johnou** [comment]
Haha it's not old hardware it's just small to save money, one of those small / micro? T2 burst machines.
