### ISSUE TITLE
NullPointerException when accessing parameter annotations

### ISSUE THREAD

**Issue by andresviedma** [classgraph/classgraph#246]
When method parameter annotations are accessed a NullPointerException is thrown.
Example code:
```
public class ClassGraphParametersBug {
   public static void main(String[] args) throws Exception {
      ScanResult scan = new ClassGraph()
            .whitelistClasses(ClassGraphParametersBug.class.getName())
            .enableAllInfo()
            .scan();
      
      ClassInfo ifeis = scan.getClassInfo(ClassGraphParametersBug.class.getName());
      MethodInfo met = ifeis.getMethodInfo().get(0);
      
      MethodParameterInfo par = met.getParameterInfo()[0];
      par.getAnnotationInfo();  // BOOOOOM
      
      System.out.println("OK");  // No, not ok at all
   }
}
```
Stack trace:
```
Exception in thread "main" java.lang.NullPointerException
	at io.github.classgraph.MethodParameterInfo.getAnnotationInfo(MethodParameterInfo.java:137)
	at ClassGraphParametersBug.main(ClassGraphParametersBug.java:18)
```

**Comment by lukehutch** [comment]
Many thanks @andresviedma for the bug report, with a complete PR and testcase!

Looks like what when wrong here was that `MethodParameterInfo` objects are created lazily, for efficiency, so they don't exist when `MethodInfo#setScanResult(ScanResult)` is called.

I'll release this now as 4.1.6.

**Comment by andresviedma** [comment]
So fast! Thank you!
