### ISSUE TITLE
java.lang.ClassNotFoundException with custom ModuleFInder

### ISSUE THREAD

**Issue by PashaTurok** [classgraph/classgraph#254]
In order to add .war module to JPMS layer we need to implement custom ModuleFinder. I did this [here](https://github.com/PashaTurok/warmodulefinder). However, when I use this module finder I get this 

```
Caused by: java.lang.NoClassDefFoundError: io/github/classgraph/utils/WhiteBlackList$WhiteBlackListWholeString
	at io.github.classgraph@4.2.2-SNAPSHOT/io.github.classgraph.ScanSpec.<init>(ScanSpec.java:56)
	at io.github.classgraph@4.2.2-SNAPSHOT/io.github.classgraph.ClassGraph.<init>(ClassGraph.java:58)
	at com.orga.webserver.core/com.orga.webserver.core.internal.Activator$1.onComponentStarted(Activator.java:69)
	at com.orga.alpha.core/com.orga.alpha.core.Framework.notifyObservers(Framework.java:504)
	at com.orga.alpha.core/com.orga.alpha.core.Framework.startComponent(Framework.java:315)
Caused by: java.lang.ClassNotFoundException: io.github.classgraph.utils.WhiteBlackList$WhiteBlackListWholeString
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at java.base/jdk.internal.loader.Loader.loadClass(Loader.java:561)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 23 more
```
I have problem only with your library. Can you say - is there something specific in it or the problem is in my code?

**Comment by lukehutch** [comment]
That's really strange. The standard ModuleFinder works fine with the ClassGraph jar. The problem looks to be that your ModuleFinder is somehow producing a ClassLoader only able to find classes that are exported, since the problematic class is in `io.github.classgraph.utils`, which is not exported: 

https://github.com/classgraph/classgraph/blob/master/src/moditect/module-info.java

What I would do to create a minimal testcase for this would be create a new library with two packages, `x.a` and `x.b`. Export `x.a` but not `x.b` in the module descriptor, then add a class `x.a.A` that refers to a class `x.b.B` in a method. Then try creating a new ModuleLayer with your code, and call the method in `x.a.A`. You should get the same exact error message (and you shouldn't get the error message if you just add the library to the module path in the normal way. If you can duplicate this behavior, then the problem is definitely not in ClassGraph. Let me know what you find.

**Comment by PashaTurok** [comment]
@lukehutch Thank you for your help. Yes, the problem was in my code. So I am closing this issue.

**Comment by lukehutch** [comment]
OK, thanks for verifying!
