### ISSUE TITLE
verbose() throws exception for anonymous classes of which the parent has a vararg constructor.

### ISSUE THREAD

**Issue by michaelzangl** [classgraph/classgraph#260]
Happens when additionally passing local variables to the child class.

```java
package test;

public abstract class P {
	public P(String...strings) {
	}

	abstract String test();
}

```
```java
package test;

public class Outer {
	public P createAnonymous(String test) {
		// internally, java adds a String parameter to the end of the method signature to pass on the test variable.
		return new P("a", "b") {
			@Override
			String test() {
				return test;
			}
		};
	}
}
```

Scan with:
```java
new ClassGraph().verbose().whitelistPackages("test").enableAllInfo().scan()
```

Stack trace:
```
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: Exception while scanning
  at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1050)
  at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1074)
  at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1090)
...
Caused by: java.util.concurrent.ExecutionException: Exception while scanning
  at io.github.classgraph.Scanner.call(Scanner.java:634)
  at io.github.classgraph.Scanner.call(Scanner.java:61)
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Got non-array type for last parameter of varargs method <init>
  at io.github.classgraph.utils.InterruptionChecker.executionException(InterruptionChecker.java:97)
  at io.github.classgraph.utils.WorkQueue.runWorkLoop(WorkQueue.java:257)
  at io.github.classgraph.utils.WorkQueue.runWorkQueue(WorkQueue.java:147)
  at io.github.classgraph.utils.WorkQueue.runWorkQueue(WorkQueue.java:180)
  at io.github.classgraph.Scanner.call(Scanner.java:549)
  ... 1 more
Caused by: java.lang.IllegalArgumentException: Got non-array type for last parameter of varargs method <init>
  at io.github.classgraph.MethodInfo.toString(MethodInfo.java:708)
  at io.github.classgraph.utils.Join.join(Join.java:51)
  at io.github.classgraph.ClassInfoUnlinked.logTo(ClassInfoUnlinked.java:177)
  at io.github.classgraph.ClasspathElement.parseClassfiles(ClasspathElement.java:247)
  at io.github.classgraph.Scanner$5.processWorkUnit(Scanner.java:553)
  at io.github.classgraph.Scanner$5.processWorkUnit(Scanner.java:550)
  at io.github.classgraph.utils.WorkQueue.runWorkLoop(WorkQueue.java:245)
  ... 4 more

```

**Comment by lukehutch** [comment]
Thanks for this bug report.

It turns out the Java compiler tacks on captured variables as constructor arguments *after* varargs parameters, which I didn't know was a thing... so the full signature of this constructor becomes:

```
<init>(final mandated io.github.classgraph.issues.issue260.Outer this$0, java.lang.String... strings, final synthetic java.lang.String val$test)
```

This is fixed and released in 4.4.2.
