### ISSUE TITLE
ArrayIndexOutOfBoundsException at  io.github.classgraph.Classfile.getConstantPoolStringOffset

### ISSUE THREAD

**Issue by ahamana** [classgraph/classgraph#319]
I encounter the following exception with 4.8.1.
\* This happens on only Linux of my production site, and I cannot reproduce my local windows environment.
So, I am thinking a way to obtain verbose log now, If I can obtain the log, I feedback to you.
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
        at io.github.classgraph.Classfile.getConstantPoolStringOffset(Classfile.java:449)
        at io.github.classgraph.Classfile.getConstantPoolString(Classfile.java:539)
        at io.github.classgraph.Classfile.getConstantPoolString(Classfile.java:557)
        at io.github.classgraph.Classfile.readClassAttributes(Classfile.java:1310)
        at io.github.classgraph.Classfile.<init>(Classfile.java:1398)
        at io.github.classgraph.Scanner$ClassfileScannerWorkUnitProcessor.processWorkUnit(Scanner.java:592)
        at io.github.classgraph.Scanner$ClassfileScannerWorkUnitProcessor.processWorkUnit(Scanner.java:545)
        at nonapi.io.github.classgraph.concurrency.WorkQueue.runWorkLoop(WorkQueue.java:245)
        at nonapi.io.github.classgraph.concurrency.WorkQueue.access$000(WorkQueue.java:50)
        at nonapi.io.github.classgraph.concurrency.WorkQueue$1.call(WorkQueue.java:201)
        at nonapi.io.github.classgraph.concurrency.WorkQueue$1.call(WorkQueue.java:198)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more
```

**Comment by lukehutch** [comment]
Based on the line number, that is an unusual bug. Can you see which classfile causes the error? Can you please attach that one classfile if possible, or if not, can you please email it to me? luke.hutch@gmail.com . I will delete the classfile after diagnosing the bug, if it is proprietary.

**Comment by ahamana** [comment]
@lukehutch I will include ClassGraph source to my application and then add some debug print to know which class file causes the error.

**Comment by lukehutch** [comment]
@ahamana Thanks. I also just committed a change to master that will give better debug output (in particular, it should show which classfile this is failing for in the verbose logs). Please generate logs in your production environment, if you are not able to replicate this in a standalone minimal testcase project.

**Comment by ahamana** [comment]
@lukehutch Thanks. I will use the latest master.

**Comment by ahamana** [comment]
@lukehutch I have obtained the verbose logs.
- 4.8.1.log (with 4.8.1 source)
- current-master.log (with current master source)

If using the current master source, the exception was not thrown.

[debug-log.zip](https://github.com/classgraph/classgraph/files/2871645/debug-log.zip)

**Comment by ahamana** [comment]
@lukehutch The issue jar file is here.
[issue-jar.zip](https://github.com/classgraph/classgraph/files/2871659/issue-jar.zip)

**Comment by lukehutch** [comment]
@ahamana Sorry for the delay, somehow I didn't get notified when you uploaded those two attachments! It looks like the following file is the one that had the issue -- can you please upload just this classfile?

`jar:file:/opt/payara/domains/domain1/osgi-cache/felix/bundle327/version0.0/bundle.jar!/module-info.class`

This is only a `module-info.class` file, so it shouldn't affect your scan results, and also ClassGraph should not stop scanning after hitting this sort of problem now.

**Comment by ahamana** [comment]
@lukehutch Many thanks for investigating the cause of the issue.
The "module-info.class" is in the attached issu-jar.zip.
I have put only the "module-info.class" in the issue-class.zip.

[issue-class.zip](https://github.com/classgraph/classgraph/files/2878196/issue-class.zip)

**Comment by lukehutch** [comment]
@ahamana I looked at the classfile, and it is actually incorrect. It uses a constant pool index of 4 for the module name (in the `Module` class attribute), and there are definitely only valid constant pool entries with indices of `[1,3]` inclusive. Where did this module descriptor come from? I will try reporting the problem to that project.

I will push out 4.8.2 shortly with the fix for skipping invalid classfiles like this one.

**Comment by lukehutch** [comment]
@ahamana Released in 4.8.2. Thanks for the report! Please still let me know the source of the invalid classfile, but I'll close this.

**Comment by ahamana** [comment]
@lukehutch Many thanks for fixing the issue.
The issue might have been reported on eclipse-ee4j/glassfish-hk2#410.

**Comment by lukehutch** [comment]
@ahamana that does look like the same issue (or something very much like it). Thanks for the link!
