### ISSUE TITLE
Exception when scanning array class literal with enableInterClassDependencies

### ISSUE THREAD

**Issue by bradnewman** [classgraph/classgraph#355]
When there is an annotation with an array class literal, and `enableInterClassDependencies()` is enabled, `scan()` throws a ClassGraphException.

Gist with full test cases and stack trace here: https://gist.github.com/bradnewman/b76bfc191c94ae6d0f4feb67c9472d5d

The problem seems to occur when somewhere in the classes being scanned, there is a Class literal like `Foo[].class` in an annotation:

    @AnnotationWithClass(AnnotationWithClassTest[].class)
    public class AnnotationWithClassTest { ... }

And ClassGraph is configured with `enableInterClassDependencies()`:

    new ClassGraph().enableInterClassDependencies().scan(); // throws ClassGraphException

I've tried enabling `verbose()`, but in this case ClassGraph does not seem to print anything to stderr before throwing the exception.

When I individually enable all of the dependencies of `enableInterClassDependencies()` (e.g. `enableClassInfo()` and `ignoreClassVisibility()`) but don't enable inter-class dependencies, the `scan()` call completes successfully and appears to contain the expected data.

Here's the part of the stack trace that seems most relevant:

    Caused by: java.lang.IllegalArgumentException: Got unexpected type io.github.classgraph.ArrayTypeSignature for ref type signature: [Lcom/example/AnnotationWithClassTest;
    	at io.github.classgraph.AnnotationClassRef.getClassName(AnnotationClassRef.java:145)
    	at io.github.classgraph.ObjectTypedValueWrapper.findReferencedClassNames(ObjectTypedValueWrapper.java:546)
    	at io.github.classgraph.AnnotationParameterValue.findReferencedClassNames(AnnotationParameterValue.java:146)
    	at io.github.classgraph.AnnotationInfo.findReferencedClassNames(AnnotationInfo.java:242)
    	at io.github.classgraph.AnnotationInfoList.findReferencedClassNames(AnnotationInfoList.java:300)
    	at io.github.classgraph.ClassInfo.findReferencedClassNames(ClassInfo.java:2730)
    	at io.github.classgraph.ScanResultObject.findReferencedClassNames(ScanResultObject.java:65)
    	at io.github.classgraph.ScanResult.indexResourcesAndClassInfo(ScanResult.java:320)
    	at io.github.classgraph.ScanResult.<init>(ScanResult.java:267)
    	at io.github.classgraph.Scanner.performScan(Scanner.java:875)

**Comment by lukehutch** [comment]
@bradnewman Thanks for the report! Fixed and released in 4.8.42.

**Comment by bradnewman** [comment]
Confirmed this is now working with 4.8.42 in my full application.  Awesome, thanks @lukehutch!

**Comment by lukehutch** [comment]
It was easy to find and fix thanks to your exemplary bug report!

I'll have to also improve logging in cases like this where an unexpected exception occurs, so I'll check that in soon. You can also call `ClassGraph#enableRealtimeLogging() ` for cases like this where ClassGraph dies before the logger outputs anything (although that's very rare, so hopefully you won't need it again...)

**Comment by lukehutch** [comment]
@bradnewman I made a number of other changes to make sure array classes work more consistently and reliably -- released in 4.8.43 (you should upgrade to this version). Thanks!
