### ISSUE TITLE
Usage of java.util.Spliterator prevents scanning on java 7

### ISSUE THREAD

**Issue by henriklen** [classgraph/classgraph#363]
In commit [a499d1bb40e0c83dbe686d2583c201a9f4f6e4b0](https://github.com/classgraph/classgraph/commit/a499d1bb40e0c83dbe686d2583c201a9f4f6e4b0) java.util.Spliterator was added to FieldInfoList. When running classgraph on Java 7 this results i a ClassNotFoundException:

io.github.classgraph.ClassGraphException: Uncaught exception during scan
	at io.github.classgraph.ClassGraphException.newClassGraphException(ClassGraphException.java:89)
	at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1183)
	at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1201)
	at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1214)
	at se.fast2.properties.PropertyInspector.execute(PropertyInspector.java:53)
	at se.fast2.PropertyInespectorMojo.execute(PropertyInespectorMojo.java:40)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.jvnet.hudson.maven3.launcher.Maven3Launcher.main(Maven3Launcher.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:329)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:239)
	at org.jvnet.hudson.maven3.agent.Maven3Main.launch(Maven3Main.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:136)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:71)
	at hudson.remoting.UserRequest.perform(UserRequest.java:121)
	at hudson.remoting.UserRequest.perform(UserRequest.java:49)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: java/util/Spliterator
	at io.github.classgraph.FieldInfoList.<clinit>(FieldInfoList.java:43)
	at io.github.classgraph.Classfile.readFields(Classfile.java:1271)
	at io.github.classgraph.Classfile.<init>(Classfile.java:1584)
	at io.github.classgraph.Scanner$ClassfileScannerWorkUnitProcessor.processWorkUnit(Scanner.java:597)
	at io.github.classgraph.Scanner$ClassfileScannerWorkUnitProcessor.processWorkUnit(Scanner.java:532)
	at nonapi.io.github.classgraph.concurrency.WorkQueue.runWorkLoop(WorkQueue.java:245)
	at nonapi.io.github.classgraph.concurrency.WorkQueue.runWorkQueue(WorkQueue.java:161)
	at io.github.classgraph.Scanner.processWorkUnits(Scanner.java:322)
	at io.github.classgraph.Scanner.performScan(Scanner.java:834)
	at io.github.classgraph.Scanner.openClasspathElementsThenScan(Scanner.java:972)
	at io.github.classgraph.Scanner.call(Scanner.java:1007)
	at io.github.classgraph.Scanner.call(Scanner.java:74)
	... 4 more
Caused by: java.lang.ClassNotFoundException: java.util.Spliterator
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
	... 16 more

I got this exception using 4.8.43 and downgraded to 4.8.38 that does not use java.util.Spliterator and thus works fine with java 7.

**Comment by lukehutch** [comment]
Thanks for this report. The "Animal Sniffer" Java API version checker failed to detect this...

https://github.com/mojohaus/animal-sniffer/issues/66

I'll replace this usage with something else.

**Comment by lukehutch** [comment]
This should be fixed, and will be released in a couple of days once the other open issue (a feature request) is closed. Thanks for your report!

**Comment by lukehutch** [comment]
Released in 4.8.44. Thanks for the report!
