### ISSUE TITLE
java.lang.IllegalArgumentException: Class java.lang.Class does not have an accessible default (no-arg) constructor

### ISSUE THREAD

**Issue by petehale** [classgraph/classgraph#368]
I am doing a scan of a very large jar file. The scan succeeds, but when an attempt is made to serialize the scan results to JSON the following exception is thrown.

Code

`      
        ClassGraph cg = (new ClassGraph()).overrideClasspath(CP.OVERRIDES);
        cg.enableInterClassDependencies();
        cg.enableAllInfo();
        ScanResult results = cg.scan();
        File file = new File("results.json");
        FileWriter fileWriter = new FileWriter(file);
        fileWriter.write(results.toJSON(2));
        fileWriter.flush();
        fileWriter.close();
`

`
Exception in thread "main" io.github.classgraph.ClassGraphException: Could not get value of field in object: io.github.classgraph.ScanResult$SerializationFormat@5ce65a89
	at io.github.classgraph.ClassGraphException.newClassGraphException(ClassGraphException.java:89)
	at nonapi.io.github.classgraph.json.JSONSerializer.toJSONGraph(JSONSerializer.java:387)
	at nonapi.io.github.classgraph.json.JSONSerializer.serializeObject(JSONSerializer.java:478)
	at nonapi.io.github.classgraph.json.JSONSerializer.serializeObject(JSONSerializer.java:510)
	at io.github.classgraph.ScanResult.toJSON(ScanResult.java:1327)
	at tryclassgraph.tryclassgraph.App.main(App.java:44)
Caused by: io.github.classgraph.ClassGraphException: Could not get value of field in object: class java.lang.String[]
	at io.github.classgraph.ClassGraphException.newClassGraphException(ClassGraphException.java:89)
	at nonapi.io.github.classgraph.json.JSONSerializer.toJSONGraph(JSONSerializer.java:387)
	at nonapi.io.github.classgraph.json.JSONSerializer.convertVals(JSONSerializer.java:192)
	at nonapi.io.github.classgraph.json.JSONSerializer.toJSONGraph(JSONSerializer.java:335)
	at nonapi.io.github.classgraph.json.JSONSerializer.convertVals(JSONSerializer.java:192)
	at nonapi.io.github.classgraph.json.JSONSerializer.toJSONGraph(JSONSerializer.java:376)
	... 4 more
Caused by: io.github.classgraph.ClassGraphException: Could not get value of field in object: java.lang.String[]
	at io.github.classgraph.ClassGraphException.newClassGraphException(ClassGraphException.java:89)
	at nonapi.io.github.classgraph.json.JSONSerializer.toJSONGraph(JSONSerializer.java:387)
	at nonapi.io.github.classgraph.json.JSONSerializer.convertVals(JSONSerializer.java:192)
	at nonapi.io.github.classgraph.json.JSONSerializer.toJSONGraph(JSONSerializer.java:376)
	... 8 more
Caused by: java.lang.IllegalArgumentException: Class java.lang.Class does not have an accessible default (no-arg) constructor
	at nonapi.io.github.classgraph.json.ClassFieldCache.getDefaultConstructorForConcreteTypeOf(ClassFieldCache.java:215)
	at nonapi.io.github.classgraph.json.FieldTypeInfo.<init>(FieldTypeInfo.java:176)
	at nonapi.io.github.classgraph.json.ClassFields.<init>(ClassFields.java:125)
	at nonapi.io.github.classgraph.json.ClassFieldCache.get(ClassFieldCache.java:135)
	at nonapi.io.github.classgraph.json.JSONSerializer.toJSONGraph(JSONSerializer.java:363)
	... 10 more
`

**Comment by lukehutch** [comment]
@petehale Thanks for the report. Should be fixed in 4.8.48 (verified with a unit test). Please test and let me know, and if doesn't fix the issue, I will re-open this bug.

**Comment by lukehutch** [comment]
There have been issues with deployment of jars to Maven Central for the past few weeks, but they should be fixed now. ClassGraph version 4.8.48 should be in Maven Central in a few hours, with the fix for this bug. Sorry for the delay.
