### ISSUE TITLE
getClassInfo() cannot be called here

### ISSUE THREAD

**Issue by johndevs** [classgraph/classgraph#375]
When updating to latest version (4.8.48) I started to get the following error:

```
Caused by: java.lang.IllegalArgumentException: getClassInfo() cannot be called here

    	at io.github.classgraph.BaseTypeSignature.getClassInfo(BaseTypeSignature.java:248)

    	at io.github.classgraph.AnnotationClassRef.getClassInfo(AnnotationClassRef.java:165)

    	at io.github.classgraph.ObjectTypedValueWrapper.findReferencedClassInfo(ObjectTypedValueWrapper.java:563)

    	at io.github.classgraph.AnnotationParameterValue.findReferencedClassInfo(AnnotationParameterValue.java:150)

    	at io.github.classgraph.AnnotationParameterValueList.findReferencedClassInfo(AnnotationParameterValueList.java:95)

    	at io.github.classgraph.ClassInfo.findReferencedClassInfo(ClassInfo.java:2758)

    	at io.github.classgraph.ScanResultObject.findReferencedClassInfo(ScanResultObject.java:67)

    	at io.github.classgraph.ScanResult.indexResourcesAndClassInfo(ScanResult.java:320)

    	at io.github.classgraph.ScanResult.<init>(ScanResult.java:267)

    	at io.github.classgraph.Scanner.performScan(Scanner.java:877)

    	at io.github.classgraph.Scanner.openClasspathElementsThenScan(Scanner.java:972)

    	at io.github.classgraph.Scanner.call(Scanner.java:1007)

    	at io.github.classgraph.Scanner.call(Scanner.java:74)
```

**Comment by lukehutch** [comment]
Fixed and released as 4.8.49. Thanks for reporting!
