### ISSUE TITLE
Getting Exception IllegalArgumentException: getClassInfo() cannot be called here

### ISSUE THREAD

**Issue by jdeppe-pivotal** [classgraph/classgraph#377]
I am trying to do this:
```
    ScanResult scanResult = new ClassGraph()
        .whitelistPackages()
        // .blacklistPackages("org.assertj")
        .enableInterClassDependencies()
        .scan();
```

And am getting the following exception:
```
Exception in thread "main" io.github.classgraph.ClassGraphException: Uncaught exception during scan
	at io.github.classgraph.ClassGraphException.newClassGraphException(ClassGraphException.java:89)
	at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1183)
	at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1201)
	at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1214)
	at io.pivotal.dependencyfinder.ClassGraphDependencyFinder.process(ClassGraphDependencyFinder.java:24)
	at io.pivotal.dependencyfinder.ClassGraphDependencyFinder.main(ClassGraphDependencyFinder.java:33)
Caused by: java.lang.IllegalArgumentException: getClassInfo() cannot be called here
	at io.github.classgraph.BaseTypeSignature.getClassInfo(BaseTypeSignature.java:248)
	at io.github.classgraph.AnnotationClassRef.getClassInfo(AnnotationClassRef.java:165)
	at io.github.classgraph.ObjectTypedValueWrapper.findReferencedClassInfo(ObjectTypedValueWrapper.java:550)
	at io.github.classgraph.AnnotationParameterValue.findReferencedClassInfo(AnnotationParameterValue.java:150)
	at io.github.classgraph.AnnotationParameterValueList.findReferencedClassInfo(AnnotationParameterValueList.java:95)
	at io.github.classgraph.ClassInfo.findReferencedClassInfo(ClassInfo.java:2758)
	at io.github.classgraph.ScanResultObject.findReferencedClassInfo(ScanResultObject.java:67)
	at io.github.classgraph.ScanResult.indexResourcesAndClassInfo(ScanResult.java:320)
	at io.github.classgraph.ScanResult.<init>(ScanResult.java:267)
	at io.github.classgraph.Scanner.performScan(Scanner.java:877)
	at io.github.classgraph.Scanner.openClasspathElementsThenScan(Scanner.java:972)
	at io.github.classgraph.Scanner.call(Scanner.java:1007)
	at io.github.classgraph.Scanner.call(Scanner.java:74)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Weirdly enough it appears this is due to having `assertj-core` on my classpath:
```
    compile('org.assertj:assertj-core:3.13.2')
```

**Comment by lukehutch** [comment]
@jdeppe-pivotal Can you please try the latest version? This should have been fixed in 4.8.49, released a couple of weeks ago (#375). The latest version is 4.8.52.

**Comment by jdeppe-pivotal** [comment]
Ah right - IntelliJ was only offering me `4.8.47` and I should have explicitly checked for a newer version.

**Comment by lukehutch** [comment]
No problem! Thanks for the report.
