### ISSUE TITLE
Unable to read nested jar files

### ISSUE THREAD

**Issue by nsoft** [classgraph/classgraph#423]
I've been trying to implement a class loader handler for jars produced by uno-jar (https://github.com/nsoft/uno-jar) which I intend to contribute here and use in JesterJ (https://github.com/nsoft/jesterj). I'm moving away from reflections, but I'm running into the following problem. Below is an excerpt from a 119M log output...  (customer name has been redacted here, and redacting customer info from a 119M log file is intractable)

```
2020-04-29T21:13:24.795+0000    ClassGraph      Opening classpath elements
2020-04-29T21:13:24.806+0000    ClassGraph      -- Opening classpath element /mnt/data1/jesterj/customer-demo-dep-0.1-SNAPSHOT.jar!/lib/commons-codec-1.11.jar!/org/apache/commons/codec/language/bm/Rule$1.class
2020-04-29T21:13:24.806+0000    ClassGraph      ---- Opening jar: /mnt/data1/jesterj/customer-demo-dep-0.1-SNAPSHOT.jar!/lib/commons-codec-1.11.jar!/org/apache/commons/codec/language/bm/Rule$1.class
2020-04-29T21:13:24.815+0000    ClassGraph      ------ Deflating nested zip entry: jar:file:/mnt/data1/jesterj/customer-demo-dep-0.1-SNAPSHOT.jar!/lib/commons-codec-1.11.jar ; uncompressed size: 335042
2020-04-29T21:13:24.818+0000    ClassGraph      ------ Getting zipfile slice [/mnt/data1/jesterj/customer-demo-dep-0.1-SNAPSHOT.jar!/lib/commons-codec-1.11.jar -> null ; byte range: 0..335042 / 335042] for nested jar lib/commons-codec-1.11.jar
2020-04-29T21:13:24.823+0000    ClassGraph      -------- Found Automatic-Module-Name entry in manifest file: org.apache.commons.codec
2020-04-29T21:13:24.823+0000    ClassGraph      ------ Deflating nested zip entry: jar:file:/mnt/data1/jesterj/customer-demo-dep-0.1-SNAPSHOT.jar!/lib/commons-codec-1.11.jar!/org/apache/commons/codec/language/bm/Rule$1.class ; uncompressed size: 641
2020-04-29T21:13:24.823+0000    ClassGraph      ------ Getting zipfile slice [/mnt/data1/jesterj/customer-demo-dep-0.1-SNAPSHOT.jar!/lib/commons-codec-1.11.jar!/org/apache/commons/codec/language/bm/Rule$1.class -> null ; byte range: 0..641 / 641] for nested jar org/apache/commons/codec/language/bm/Rule$1.class
2020-04-29T21:13:24.824+0000    ClassGraph      ------ Could not open jarfile /mnt/data1/jesterj/customer-demo-dep-0.1-SNAPSHOT.jar!/lib/commons-codec-1.11.jar!/org/apache/commons/codec/language/bm/Rule$1.class : java.io.IOException: Jarfile central directory signature not found: /mnt/data1/jesterj/customer-demo-dep-0.1-SNAPSHOT.jar!/lib/commons-codec-1.11.jar!/org/apache/commons/codec/language/bm/Rule$1.class
2020-04-29T21:13:24.806+0000    ClassGraph      -- Opening classpath element /mnt/data1/jesterj/customer-demo-dep-0.1-SNAPSHOT.jar!/lib/lucene-core-7.5.0.jar!/org/apache/lucene/index/LiveIndexWriterConfig.class
2020-04-29T21:13:24.809+0000    ClassGraph      ---- Opening jar: /mnt/data1/jesterj/customer-demo-dep-0.1-SNAPSHOT.jar!/lib/lucene-core-7.5.0.jar!/org/apache/lucene/index/LiveIndexWriterConfig.class
2020-04-29T21:13:24.830+0000    ClassGraph      ------ Deflating nested zip entry: jar:file:/mnt/data1/jesterj/customer-demo-dep-0.1-SNAPSHOT.jar!/lib/lucene-core-7.5.0.jar ; uncompressed size: 3056210
2020-04-29T21:13:24.960+0000    ClassGraph      ------ Getting zipfile slice [/mnt/data1/jesterj/customer-demo-dep-0.1-SNAPSHOT.jar!/lib/lucene-core-7.5.0.jar -> null ; byte range: 0..3056210 / 3056210] for nested jar lib/lucene-core-7.5.0.jar
2020-04-29T21:13:24.986+0000    ClassGraph      -------- This is a multi-release jar, with versions: 9
2020-04-29T21:13:24.987+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/analysis/tokenattributes/CharTermAttributeImpl.class masks org/apache/lucene/analysis/tokenattributes/CharTermAttributeImpl.class
2020-04-29T21:13:24.987+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/codecs/compressing/LZ4.class masks org/apache/lucene/codecs/compressing/LZ4.class
2020-04-29T21:13:24.987+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/document/BinaryPoint$2.class masks org/apache/lucene/document/BinaryPoint$2.class
2020-04-29T21:13:24.987+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/document/DoubleRange.class masks org/apache/lucene/document/DoubleRange.class
2020-04-29T21:13:24.987+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/document/FloatRange.class masks org/apache/lucene/document/FloatRange.class
2020-04-29T21:13:24.987+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/document/IntRange.class masks org/apache/lucene/document/IntRange.class
2020-04-29T21:13:24.987+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/document/LatLonPointDistanceQuery$1$2.class masks org/apache/lucene/document/LatLonPointDistanceQuery$1$2.class
2020-04-29T21:13:24.987+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/document/LatLonPointDistanceQuery$1$3.class masks org/apache/lucene/document/LatLonPointDistanceQuery$1$3.class
2020-04-29T21:13:24.987+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/document/LatLonPointInPolygonQuery$1$1.class masks org/apache/lucene/document/LatLonPointInPolygonQuery$1$1.class
2020-04-29T21:13:24.987+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/document/LongRange.class masks org/apache/lucene/document/LongRange.class
2020-04-29T21:13:24.987+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/document/RangeFieldQuery$QueryType$1.class masks org/apache/lucene/document/RangeFieldQuery$QueryType$1.class
2020-04-29T21:13:24.987+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/document/RangeFieldQuery$QueryType$2.class masks org/apache/lucene/document/RangeFieldQuery$QueryType$2.class
2020-04-29T21:13:24.987+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/document/RangeFieldQuery$QueryType$3.class masks org/apache/lucene/document/RangeFieldQuery$QueryType$3.class
2020-04-29T21:13:24.987+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/index/BitsSlice.class masks org/apache/lucene/index/BitsSlice.class
2020-04-29T21:13:24.987+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/index/CheckIndex$VerifyPointsVisitor.class masks org/apache/lucene/index/CheckIndex$VerifyPointsVisitor.class
2020-04-29T21:13:24.987+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/index/CodecReader.class masks org/apache/lucene/index/CodecReader.class
2020-04-29T21:13:24.988+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/index/MergeReaderWrapper.class masks org/apache/lucene/index/MergeReaderWrapper.class
2020-04-29T21:13:24.988+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/index/PointValues.class masks org/apache/lucene/index/PointValues.class
2020-04-29T21:13:24.988+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/search/BooleanScorer$TailPriorityQueue.class masks org/apache/lucene/search/BooleanScorer$TailPriorityQueue.class
2020-04-29T21:13:24.988+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/search/PointInSetQuery$SinglePointVisitor.class masks org/apache/lucene/search/PointInSetQuery$SinglePointVisitor.class
2020-04-29T21:13:24.988+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/search/PointRangeQuery$1$1.class masks org/apache/lucene/search/PointRangeQuery$1$1.class
2020-04-29T21:13:24.988+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/search/PointRangeQuery$1$2.class masks org/apache/lucene/search/PointRangeQuery$1$2.class
2020-04-29T21:13:24.988+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/search/PointRangeQuery$1.class masks org/apache/lucene/search/PointRangeQuery$1.class
2020-04-29T21:13:24.988+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/util/BytesRef.class masks org/apache/lucene/util/BytesRef.class
2020-04-29T21:13:24.988+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/util/BytesRefArray.class masks org/apache/lucene/util/BytesRefArray.class
2020-04-29T21:13:24.988+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/util/CharsRef$UTF16SortedAsUTF8Comparator.class masks org/apache/lucene/util/CharsRef$UTF16SortedAsUTF8Comparator.class
2020-04-29T21:13:24.988+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/util/CharsRef.class masks org/apache/lucene/util/CharsRef.class
2020-04-29T21:13:24.988+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/util/IntsRef.class masks org/apache/lucene/util/IntsRef.class
2020-04-29T21:13:24.988+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/util/LongsRef.class masks org/apache/lucene/util/LongsRef.class
2020-04-29T21:13:24.988+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/util/StringHelper.class masks org/apache/lucene/util/StringHelper.class
2020-04-29T21:13:24.988+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/util/automaton/Automaton$Builder.class masks org/apache/lucene/util/automaton/Automaton$Builder.class
2020-04-29T21:13:24.988+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/util/automaton/Automaton.class masks org/apache/lucene/util/automaton/Automaton.class
2020-04-29T21:13:24.988+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/util/bkd/BKDReader.class masks org/apache/lucene/util/bkd/BKDReader.class
2020-04-29T21:13:24.988+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/util/bkd/BKDWriter$BKDMergeQueue.class masks org/apache/lucene/util/bkd/BKDWriter$BKDMergeQueue.class
2020-04-29T21:13:24.988+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/util/bkd/BKDWriter.class masks org/apache/lucene/util/bkd/BKDWriter.class
2020-04-29T21:13:24.988+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/util/bkd/MutablePointsReaderUtils$1$1.class masks org/apache/lucene/util/bkd/MutablePointsReaderUtils$1$1.class
2020-04-29T21:13:24.988+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/util/bkd/MutablePointsReaderUtils$2.class masks org/apache/lucene/util/bkd/MutablePointsReaderUtils$2.class
2020-04-29T21:13:24.988+0000    ClassGraph      -------- META-INF/versions/9/org/apache/lucene/util/bkd/MutablePointsReaderUtils$3$1.class masks org/apache/lucene/util/bkd/MutablePointsReaderUtils$3$1.class
2020-04-29T21:13:24.988+0000    ClassGraph      ------ Deflating nested zip entry: jar:file:/mnt/data1/jesterj/customer-demo-dep-0.1-SNAPSHOT.jar!/lib/lucene-core-7.5.0.jar!/org/apache/lucene/index/LiveIndexWriterConfig.class ; uncompressed size: 9225
2020-04-29T21:13:24.989+0000    ClassGraph      ------ Getting zipfile slice [/mnt/data1/jesterj/customer-demo-dep-0.1-SNAPSHOT.jar!/lib/lucene-core-7.5.0.jar!/org/apache/lucene/index/LiveIndexWriterConfig.class -> null ; byte range: 0..9225 / 9225] for nested jar org/apache/lucene/index/LiveIndexWriterConfig.class
2020-04-29T21:13:24.990+0000    ClassGraph      ------ Could not open jarfile /mnt/data1/jesterj/customer-demo-dep-0.1-SNAPSHOT.jar!/lib/lucene-core-7.5.0.jar!/org/apache/lucene/index/LiveIndexWriterConfig.class : java.io.IOException: Jarfile central directory signature not found: /mnt/data1/jesterj/customer-demo-dep-0.1-SNAPSHOT.jar!/lib/lucene-core-7.5.0.jar!/org/apache/lucene/index/LiveIndexWriterConfig.class
2020-04-29T21:13:24.806+0000    ClassGraph      -- Opening classpath element /mnt/data1/jesterj/customer-demo-dep-0.1-SNAPSHOT.jar!/lib/tika-core-1.16.jar!/org/apache/tika/sax/xpath/SubtreeMatcher.class
```

Prior to that there's a lot of messages about ignoring duplicate stuff, but that doesn't seem to be an error of any sort. This is the first suspicious point... after hundreds (thousands?) of sections like the two above, complaining about central directory signature not found, I eventually get: 

```
2020-04-30T13:33:42.350+0000	ClassGraph	Uncaught exception during scan
2020-04-30T13:33:42.350+0000	ClassGraph	-- java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 34
2020-04-30T13:33:42.350+0000	ClassGraph	-- 	at nonapi.io.github.classgraph.fileslice.reader.RandomAccessArrayReader.readInt(RandomAccessArrayReader.java:142)
2020-04-30T13:33:42.350+0000	ClassGraph	-- 	at nonapi.io.github.classgraph.fastzipfilereader.LogicalZipFile.readCentralDirectory(LogicalZipFile.java:451)
2020-04-30T13:33:42.350+0000	ClassGraph	-- 	at nonapi.io.github.classgraph.fastzipfilereader.LogicalZipFile.<init>(LogicalZipFile.java:155)
2020-04-30T13:33:42.350+0000	ClassGraph	-- 	at nonapi.io.github.classgraph.fastzipfilereader.NestedJarHandler$3.newInstance(NestedJarHandler.java:144)
2020-04-30T13:33:42.350+0000	ClassGraph	-- 	at nonapi.io.github.classgraph.fastzipfilereader.NestedJarHandler$3.newInstance(NestedJarHandler.java:139)
2020-04-30T13:33:42.350+0000	ClassGraph	-- 	at nonapi.io.github.classgraph.concurrency.SingletonMap.get(SingletonMap.java:189)
2020-04-30T13:33:42.350+0000	ClassGraph	-- 	at nonapi.io.github.classgraph.fastzipfilereader.NestedJarHandler$4.newInstance(NestedJarHandler.java:323)
2020-04-30T13:33:42.350+0000	ClassGraph	-- 	at nonapi.io.github.classgraph.fastzipfilereader.NestedJarHandler$4.newInstance(NestedJarHandler.java:154)
2020-04-30T13:33:42.350+0000	ClassGraph	-- 	at nonapi.io.github.classgraph.concurrency.SingletonMap.get(SingletonMap.java:189)
2020-04-30T13:33:42.350+0000	ClassGraph	-- 	at io.github.classgraph.ClasspathElementZip.open(ClasspathElementZip.java:141)
2020-04-30T13:33:42.350+0000	ClassGraph	-- 	at io.github.classgraph.Scanner$3.processWorkUnit(Scanner.java:581)
2020-04-30T13:33:42.350+0000	ClassGraph	-- 	at io.github.classgraph.Scanner$3.processWorkUnit(Scanner.java:553)
2020-04-30T13:33:42.350+0000	ClassGraph	-- 	at nonapi.io.github.classgraph.concurrency.WorkQueue.runWorkLoop(WorkQueue.java:246)
2020-04-30T13:33:42.350+0000	ClassGraph	-- 	at nonapi.io.github.classgraph.concurrency.WorkQueue.access$000(WorkQueue.java:50)
2020-04-30T13:33:42.350+0000	ClassGraph	-- 	at nonapi.io.github.classgraph.concurrency.WorkQueue$1.call(WorkQueue.java:201)
2020-04-30T13:33:42.350+0000	ClassGraph	-- 	at nonapi.io.github.classgraph.concurrency.WorkQueue$1.call(WorkQueue.java:198)
2020-04-30T13:33:42.350+0000	ClassGraph	-- 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2020-04-30T13:33:42.350+0000	ClassGraph	-- 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-04-30T13:33:42.350+0000	ClassGraph	-- 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-04-30T13:33:42.350+0000	ClassGraph	-- 	at java.base/java.lang.Thread.run(Thread.java:834)
```
This was running with the patch for #421 and the handler seen here: https://github.com/nsoft/classgraph/commit/14719d00e872bc438048d3553f01aa7803847ba2 which relies on the following enhancement to UnoJar https://github.com/nsoft/uno-jar/commit/9c59d840204826a9c881b345111d8b72df62454f

Given that there is so much going on here I can't be entirely certain that this is your problem of if it's a problem I've caused somehow, but it seems like it could be an issue with your zip reading routines... 

The unojar files are readable by java, and emacs and I have no problems browsing down into files within jars within the unojar in emacs, so it seems like the file and jar files within the file are valid.

**Comment by nsoft** [comment]
Also minor typo note: 

The message `Deflating nested zip entry` seems to refer to an inflating process not deflating :)

**Comment by nsoft** [comment]
Just to round out the picture in case you're curious this is the code knitting this all together in JesterJ https://github.com/nsoft/jesterj/commit/06712fc9b2f003051ab2aea210b003e8ee948fe6

**Comment by nsoft** [comment]
[issue423.tar.gz](https://github.com/classgraph/classgraph/files/4559939/issue423.tar.gz)

Simplified example test case

**Comment by lukehutch** [comment]
The `ArrayIndexOutOfBoundsException` almost certainly indicates a bug. I'll take a look.

However, meanwhile, I see that `JesterClassLoader` just extends `URLClassLoader`, so it should work fine with ClassGraph out of the box. However, `com.needhamsoftware.unojar.JarClassLoader` does not extend `URLClassLoader`, so it will need its own `ClassLoaderHandler` to work with ClassGraph.

On quick examination, I think a `ClassLoaderHandler` for this classloader would only need to call `JarClassLoader.getOneJarPath()`? It looks like a `lib/` directory is also supported inside the jar, presumably for nested jars, but this will already be autodetected by ClassGraph.

https://github.com/nsoft/uno-jar/blob/master/core/src/main/java/com/needhamsoftware/unojar/JarClassLoader.java

Please confirm if any more work would be needed to support this classloader, while I go look at the bug. Thanks!

**Comment by lukehutch** [comment]
I tried compiling your simplified example testcase project, but it said that `com.needhamsoftware.unojar` 1.0-SNAPSHOT was not available. So I git-cloned the `nsoft/uno-jar` repo, and tried compiling it. It said it couldn't find the same dependency, which seems circular:

```
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file '/tmp/uno-jar/tests/build.gradle' line: 16

* What went wrong:
Plugin [id: 'com.needhamsoftware.unojar', version: '1.0-SNAPSHOT'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.needhamsoftware.unojar:com.needhamsoftware.unojar.gradle.plugin:1.0-SNAPSHOT')
  Searched in the following repositories:
    MavenLocal(file:/home/luke/.m2/repository/)
    Gradle Central Plugin Repository
```

**Comment by lukehutch** [comment]
Looking at the logs, this is very suspicious:

`Opening classpath element /mnt/data1/jesterj/customer-demo-dep-0.1-SNAPSHOT.jar!/lib/lucene-core-7.5.0.jar!/org/apache/lucene/index/LiveIndexWriterConfig.class`

Individual classfiles should never be listed on the classpath. If any file is listed on the classpath, it should be a jar. This is why ClassGraph tries to open the classfile as a jar, and fails to find the central directory marker:

`Could not open jarfile /mnt/data1/jesterj/customer-demo-dep-0.1-SNAPSHOT.jar!/lib/lucene-core-7.5.0.jar!/org/apache/lucene/index/LiveIndexWriterConfig.class : java.io.IOException: Jarfile central directory signature not found: /mnt/data1/jesterj/customer-demo-dep-0.1-SNAPSHOT.jar!/lib/lucene-core-7.5.0.jar!/org/apache/lucene/index/LiveIndexWriterConfig.class`

I don't know where these classfiles would be coming from -- perhaps from a buggy `ClassLoaderHandler`, perhaps from something incorrectly listing classfiles on `java.class.path`. Can you track this down please?

**Comment by nsoft** [comment]
I was just pondering along these lines. I may have misinterpreted comments in the older code I adopted from OneJar... writing a new FileUrlFactory to avoid this now...

**Comment by lukehutch** [comment]
I fixed the `IndexOutOfBoundsException`. The problem was that non-jarfiles were being searched for zipfile "end of central directory" markers, which start 22 bytes before the end of the file, and may start as far back from the end of the file as 22+32 = 54 bytes. If the file length is less than 54 bytes long (as in this case, where the file was 34 bytes long), the for loop that was searching for this marker would try to fetch from a negative array index. Instead, an attempt to read past the beginning of the file now simply fails with an `IOException` that the central directory signature could not be found, as expected.

So actually the `IndexOutOfBoundsException` was only exposed because of the bug that I reported in my previous comment, which is that somehow raw classfile paths were ending up in the classpath, which is not what should be happening. This could be a ClassGraph bug or it could be a classloader bug.

I don't know which file was causing this exception to be thrown, since you truncated the logs, but I'm guessing it was not a classfile, since classfiles are usually longer than 34 bytes long. Can you please check, for any files that were causing this exception to be thrown, whether the reported size (e.g. 34 for `Index -1 out of bounds for length 34`) matches the uncompressed size of that entry in the zipfile? I want to make sure that the inflate code is not also truncating files (which would be an unrelated additional bug, if true).

PS I fixed the typo, thanks for that!

**Comment by lukehutch** [comment]
> I was just pondering along these lines. I may have misinterpreted comments in the older code I adopted from OneJar... writing a new FileUrlFactory to avoid this now...

Just make sure that any URLs that you provide in your `URLCLassLoader` subclass are URLs to either directories or jars, not to classfiles.

See also the comment on writing a `ClassLoaderHandler` for the OneJar classloader. It's a pretty simple process, if you look at the other `ClassLoaderHandler` instances in ClassGraph's repo, so maybe you want to even take a stab at that.

**Comment by nsoft** [comment]
I did look at several and cribbed off the tomcat one, but the classloader in question is not a subclass of URLClassloader, so that meant I had to develop my own list of URLS... and I co-opted the output of a class that operates at to fine of a detail in uno-jar, thinking that I needed to give you a list of actual class locations rather than just a classpath level. Tweaking that to omit the class portion gets me out the far end of your code. This proves the problem is as you said. Now I'm going to go back and see if just feeding it the oneJarPath is good enough now (there's also a /main directory, but that's should just an add-in for AUTOMATIC_LIB_DIR_PREFIXES). 

It would be nice if ClassLoaderHandler had methods and javadocs rather than just being a marker interface.

**Comment by lukehutch** [comment]
Yeah, `ClassLoaderHandler` is not nice as it stands. I have gone back and forth a couple of times between static and non-static methods, but I keep coming back to static methods, even though in Java, stupidly, static methods cannot be inherited or overloaded (at least before default methods were added). By making the methods static, `ClassLoaderHandler` instances are prevented from retaining any sort of state, and it also means that a new `ClassLoaderHandler` does not have to be instantiated for the cross product of every classloader and every `ClassLoaderHandler` subclass. I can't switch to using default methods, because JDK 7 is supported by ClassGraph.

**Comment by lukehutch** [comment]
Can you share your `ClassLoaderHandler`? Maybe I can offer some perspective.

I'll add `main/` to `AUTOMATIC_LIB_DIR_PREFIXES` -- I don't think it would hurt to do so.

**Comment by lukehutch** [comment]
I just checked in a `ClassLoaderHandler` that should work for both UnoJar and One-Jar. Please take a look and see if it works for your situation.

**Comment by lukehutch** [comment]
I'm pretty sure the git master version should solve the problems you have reported so far. I suspect any other issues are outside of ClassGraph at this point, but let me know if you find more problems. Also let me know if you think I should push out a release with the changes so far.

**Comment by nsoft** [comment]
Will try it out, thanks much for your help so far.

**Comment by lukehutch** [comment]
I'm going to assume that the original bug (needing `ClassLoaderHandler` support) is fixed, since you said that with your similar `ClassLoaderHandler`, you got through all the initial problems you were seeing with scanning. The other bugs found so far along the way are all patched. I'll push out these changes now in 4.8.74. Feel free to open more issues if you encounter more bugs. Thanks for the bug report!

**Comment by nsoft** [comment]
FYI, discovered that some code you were accounting for was unreachable (NPE would be thrown first)... Since it's evidently been that way since 2010, I'm just deleting it since it clearly won't be missed. https://github.com/nsoft/uno-jar/commit/a28b9072a4732bace0d4735ffc84dc0b939be9dc

**Comment by lukehutch** [comment]
OK. Feel free to submit a PR to remove the relevant code if you think nobody will ever try to use an old version of Uno-Jar with ClassGraph.
