### ISSUE TITLE
JRT - Resource.getURI() returning incorrect URI

### ISSUE THREAD

**Issue by GedMarc** [classgraph/classgraph#433]
Hey luke

On getting URL's when running in JImages they are looking like
```
jar:/jrt:/<module name>!/package
```

So I find myself doing : 
```
URI uri = URI.create(url.toString()
			                        .replace("jar:jrt:/", "jrt:/")
			                        .replace("!", ""));
```
:)
I think somewhere although jar:/ is impossible in JImages, its adding the reference and applying the "!" to the module name :)

I'll try get the verbose ready

**Comment by lukehutch** [comment]
A small test project would be helpful. But also, be aware that jrt URIs have lots of limitations that regular file URIs don't. I don't remember the details, however.

**Comment by lukehutch** [comment]
@GedMarc I just fixed #434, which may also fix this issue. Can you check, please?

**Comment by lukehutch** [comment]
Fixed and released in 4.8.84. Thanks for the report!

**Comment by GedMarc** [comment]
Sorry man - looks like this didn't work so well - 
But it's only happening on the second call to the same scan result / the first call is perfect 

```
Caused by: java.lang.IllegalArgumentException: Could not create URL from URI with "jrt:" scheme: jrt:/primefaces/META-INF/primefaces-p.taglib.xml
        at io.github.classgraph.Resource.uriToURL(Unknown Source) ~[io.github.classgraph:?]
        at io.github.classgraph.Resource.getURL(Unknown Source) ~[io.github.classgraph:?]
        at com.sun.faces.facelets.util.Classpath.lambda$search$0(Unknown Source) ~[javax.faces:?]
        at io.github.classgraph.ResourceList.forEachByteArrayThrowingIOException(Unknown Source) ~[io.github.classgraph:?]
        at com.sun.faces.facelets.util.Classpath.search(Unknown Source) ~[javax.faces:?]
        at com.sun.faces.facelets.util.Classpath.search(Unknown Source) ~[javax.faces:?]
        at com.sun.faces.config.configprovider.MetaInfFaceletTaglibraryConfigProvider.getResources(Unknown Source) ~[javax.faces:?]
        at com.sun.faces.config.manager.tasks.FindConfigResourceURIsTask.call(Unknown Source) ~[javax.faces:?]
        at com.sun.faces.config.manager.tasks.FindConfigResourceURIsTask.call(Unknown Source) ~[javax.faces:?]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
        ... 11 more
```

So literally just before i do a getResourcesMatchingPattern()/getResources() and read with success, same scan result, same method, same call, same path, only the filename is different (so JRT definitely has access to all those files)

```
Proof of reading from classgraph
Documents Reading URI - jrt:/primefaces/META-INF/faces-config.xml
JRT URL : jrt:/primefaces/META-INF/faces-config.xml
```

I've rolled back to 4.8.83 for now, i can't seem to make a work around

Attaching the verbose now now 

(this is swapping the javax.faces scanner to classgraph)

**Comment by lukehutch** [comment]
Actually that's exactly as expected. `URL` does not support the `jrt:` scheme, only `URI` does. So you need to call `Resource.getURI()`, not `Resource.getURL()`. Let me know if that fixes the issue.

**Comment by GedMarc** [comment]
erg, restricted by API, returns a URL[] https://jakarta.ee/specifications/faces/2.3/apidocs/index.html?com/sun/faces/facelets/util/Classpath.html

I understand the change, hmm 
Yeah I may have to register a new URL handler for JRT then... I thought for version 83 you had already catered for the URL switch which is why it was working lol :)

https://docs.oracle.com/javase/9/docs/api/index.html?java/net/spi/URLStreamHandlerProvider.html
If i enable the JRT protocol for URL's will this circumvent the exception?


```
	public static URL[] search(ClassLoader cl, String prefix, String suffix,
	                           com.sun.faces.facelets.util.Classpath.SearchAdvice advice)
			throws IOException	
```

**Comment by GedMarc** [comment]
ok no

https://github.com/classgraph/classgraph/blame/a0d510593e3da9f41852a1210112a0f96aa3647e/src/main/java/io/github/classgraph/Resource.java#L104

That is very wrong - it denies any possibility of actually specifying a URL protocol connection for it.

I have to use .83 - can you not allow URL to throw the error instead?

**Comment by lukehutch** [comment]
How is this wrong? Please suggest an alternative.
