### ISSUE TITLE
Problem overriding classloaders and scanResult.ToJSON()

### ISSUE THREAD

**Issue by GameEngineers** [classgraph/classgraph#457]
Hello,
Im using this Java Library (4.8.78) to scan external java compiled classes from other projects. im doing that using Classgraph.overrideClasspath(). this is my code:

```
public void scan(List<URL> urls) throws IOException {
        scanResult = classGraph
                .ignoreClassVisibility()
                .ignoreFieldVisibility()
                .ignoreMethodVisibility()
                .enableAllInfo()
                .overrideClasspath(urls)
                .ignoreParentClassLoaders()
                .scan();
        saveToJSON();
        scanResult.close();
}
private void saveToJSON() throws IOException {
        String scanResultJson = scanResult.toJSON(identJSON);
        Files.write(Paths.get(outputFilePath), scanResultJson.getBytes(), StandardOpenOption.CREATE);
    }

```

And this is my code to load all File classes from some external project:

```
private List<URL> searchFiles(String directoryPath) throws IOException {
        return Files.find(Paths.get(directoryPath),
                Integer.MAX_VALUE,
                (filePath, fileAttr) -> fileAttr.isDirectory())
                .map(Path::toUri)
                .map(this::fromURI)
                .collect(Collectors.toList());
    }

    private URL fromURI(URI uri){
        try {
            return uri.toURL();
        } catch (MalformedURLException e) {
            e.printStackTrace();
            throw new ProjectNotOpenedException(e.getMessage());
        }
}
```
 
The problem is when i save ScanResult to JSON then i have an Error. Maybe i doing something wrong, or its just a bug? This is my Error stack trace:

io.github.classgraph.ClassGraphException: Could not get value of field in object: io.github.classgraph.ScanResult$SerializationFormat@73c151f3
        at io.github.classgraph.ClassGraphException.newClassGraphException(ClassGraphException.java:89) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.toJSONGraph(JSONSerializer.java:397) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.serializeObject(JSONSerializer.java:488) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.serializeObject(JSONSerializer.java:520) ~[classgraph-4.8.78.jar:4.8.78]
        at io.github.classgraph.ScanResult.toJSON(ScanResult.java:1371) ~[classgraph-4.8.78.jar:4.8.78]
        at es.upm.miw.umlgraphql.repositories.classgraph.ClassGraphManager.saveToJSON(ClassGraphManager.java:52) ~[classes/:na]
        at es.upm.miw.umlgraphql.repositories.classgraph.ClassGraphManager.scan(ClassGraphManager.java:41) ~[classes/:na]
        at es.upm.miw.umlgraphql.utils.ProjectManager.open(ProjectManager.java:32) ~[classes/:na]
        at es.upm.miw.umlgraphql.resolvers.ProjectMutationResolver.openProject(ProjectMutationResolver.java:23) ~[classes/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
        at graphql.kickstart.tools.resolver.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:262) ~[graphql-java-tools-6.1.0.jar:na]
        at graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation.lambda$instrumentDataFetcher$0(DataLoaderDispatcherInstrumentation.java:86) ~[graphql-java-14.1.jar:na]
        at graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation$$Lambda$776/1097909457.get(Unknown Source) ~[na:na]
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:272) [graphql-java-14.1.jar:na]
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:200) [graphql-java-14.1.jar:na]
        at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:173) [graphql-java-14.1.jar:na]
        at graphql.execution.AsyncSerialExecutionStrategy.lambda$execute$1(AsyncSerialExecutionStrategy.java:41) [graphql-java-14.1.jar:na]
        at graphql.execution.AsyncSerialExecutionStrategy$$Lambda$772/950783595.apply(Unknown Source) [graphql-java-14.1.jar:na]
        at graphql.execution.Async.eachSequentiallyImpl(Async.java:77) [graphql-java-14.1.jar:na]
        at graphql.execution.Async.eachSequentially(Async.java:66) [graphql-java-14.1.jar:na]
        at graphql.execution.AsyncSerialExecutionStrategy.execute(AsyncSerialExecutionStrategy.java:36) [graphql-java-14.1.jar:na]
        at graphql.execution.Execution.executeOperation(Execution.java:165) [graphql-java-14.1.jar:na]
        at graphql.execution.Execution.execute(Execution.java:106) [graphql-java-14.1.jar:na]
        at graphql.GraphQL.execute(GraphQL.java:623) [graphql-java-14.1.jar:na]
        at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:556) [graphql-java-14.1.jar:na]
        at graphql.GraphQL.executeAsync(GraphQL.java:520) [graphql-java-14.1.jar:na]
        at graphql.kickstart.execution.GraphQLInvoker$$Lambda$492/212065138.executeAsync(Unknown Source) [graphql-java-kickstart-9.2.0.jar:na]
        at graphql.kickstart.execution.GraphQLInvoker.executeAsync(GraphQLInvoker.java:26) [graphql-java-kickstart-9.2.0.jar:na]
        at graphql.kickstart.execution.GraphQLInvoker.query(GraphQLInvoker.java:38) [graphql-java-kickstart-9.2.0.jar:na]
        at graphql.kickstart.execution.GraphQLInvoker.query(GraphQLInvoker.java:31) [graphql-java-kickstart-9.2.0.jar:na]
        at graphql.kickstart.servlet.HttpRequestHandlerImpl.invoke(HttpRequestHandlerImpl.java:67) [graphql-java-servlet-9.2.0.jar:na]
        at graphql.kickstart.servlet.HttpRequestHandlerImpl.execute(HttpRequestHandlerImpl.java:52) [graphql-java-servlet-9.2.0.jar:na]
        at graphql.kickstart.servlet.HttpRequestHandlerImpl.handle(HttpRequestHandlerImpl.java:37) [graphql-java-servlet-9.2.0.jar:na]
        at graphql.kickstart.servlet.AbstractGraphQLHttpServlet.doRequest(AbstractGraphQLHttpServlet.java:148) [graphql-java-servlet-9.2.0.jar:na]
        at graphql.kickstart.servlet.AbstractGraphQLHttpServlet.doRequestAsync(AbstractGraphQLHttpServlet.java:138) [graphql-java-servlet-9.2.0.jar:na]
        at graphql.kickstart.servlet.AbstractGraphQLHttpServlet.doPost(AbstractGraphQLHttpServlet.java:170) [graphql-java-servlet-9.2.0.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92) [spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) [spring-boot-actuator-2.3.1.RELEASE.jar:2.3.1.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_05]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_05]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
Caused by: io.github.classgraph.ClassGraphException: Could not get value of field in object: nonapi.io.github.classgraph.scanspec.ScanSpec@41fde3ac
        at io.github.classgraph.ClassGraphException.newClassGraphException(ClassGraphException.java:89) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.toJSONGraph(JSONSerializer.java:397) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.convertVals(JSONSerializer.java:196) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.toJSONGraph(JSONSerializer.java:386) ~[classgraph-4.8.78.jar:4.8.78]
        ... 80 common frames omitted
Caused by: io.github.classgraph.ClassGraphException: Could not get value of field in object: file:/H:/MASTER_ING_WEB/CURSO_2019-20/TFM/Proyectos/Damas/
        at io.github.classgraph.ClassGraphException.newClassGraphException(ClassGraphException.java:89) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.toJSONGraph(JSONSerializer.java:397) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.convertVals(JSONSerializer.java:196) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.toJSONGraph(JSONSerializer.java:345) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.convertVals(JSONSerializer.java:196) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.toJSONGraph(JSONSerializer.java:386) ~[classgraph-4.8.78.jar:4.8.78]
        ... 82 common frames omitted
Caused by: java.lang.IllegalArgumentException: Class java.net.URLStreamHandlerFactory does not have an accessible default (no-arg) constructor
        at nonapi.io.github.classgraph.json.ClassFieldCache.getDefaultConstructorForConcreteTypeOf(ClassFieldCache.java:217) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.FieldTypeInfo.<init>(FieldTypeInfo.java:180) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.ClassFields.<init>(ClassFields.java:164) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.ClassFieldCache.get(ClassFieldCache.java:137) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.toJSONGraph(JSONSerializer.java:373) ~[classgraph-4.8.78.jar:4.8.78]
        ... 86 common frames omitted

2020-07-05 12:20:55.705 ERROR 21088 --- [nio-8080-exec-1] g.k.e.error.DefaultGraphQLErrorHandler   : Error executing query Exception while fetching data (/openProject) : Could not get value of field in object: io.github.classgraph.ScanResult$SerializationFormat@73c151f3

io.github.classgraph.ClassGraphException: Could not get value of field in object: io.github.classgraph.ScanResult$SerializationFormat@73c151f3
        at io.github.classgraph.ClassGraphException.newClassGraphException(ClassGraphException.java:89) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.toJSONGraph(JSONSerializer.java:397) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.serializeObject(JSONSerializer.java:488) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.serializeObject(JSONSerializer.java:520) ~[classgraph-4.8.78.jar:4.8.78]
        at io.github.classgraph.ScanResult.toJSON(ScanResult.java:1371) ~[classgraph-4.8.78.jar:4.8.78]
        at es.upm.miw.umlgraphql.repositories.classgraph.ClassGraphManager.saveToJSON(ClassGraphManager.java:52) ~[classes/:na]
        at es.upm.miw.umlgraphql.repositories.classgraph.ClassGraphManager.scan(ClassGraphManager.java:41) ~[classes/:na]
        at es.upm.miw.umlgraphql.utils.ProjectManager.open(ProjectManager.java:32) ~[classes/:na]
        at es.upm.miw.umlgraphql.resolvers.ProjectMutationResolver.openProject(ProjectMutationResolver.java:23) ~[classes/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_05]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_05]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_05]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_05]
        at graphql.kickstart.tools.resolver.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:262) ~[graphql-java-tools-6.1.0.jar:na]
        at graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation.lambda$instrumentDataFetcher$0(DataLoaderDispatcherInstrumentation.java:86) ~[graphql-java-14.1.jar:na]
        at graphql.execution.instrumentation.dataloader.DataLoaderDispatcherInstrumentation$$Lambda$776/1097909457.get(Unknown Source) ~[na:na]
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:272) ~[graphql-java-14.1.jar:na]
        at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:200) ~[graphql-java-14.1.jar:na]
        at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:173) ~[graphql-java-14.1.jar:na]
        at graphql.execution.AsyncSerialExecutionStrategy.lambda$execute$1(AsyncSerialExecutionStrategy.java:41) ~[graphql-java-14.1.jar:na]
        at graphql.execution.AsyncSerialExecutionStrategy$$Lambda$772/950783595.apply(Unknown Source) ~[na:na]
        at graphql.execution.Async.eachSequentiallyImpl(Async.java:77) ~[graphql-java-14.1.jar:na]
        at graphql.execution.Async.eachSequentially(Async.java:66) ~[graphql-java-14.1.jar:na]
        at graphql.execution.AsyncSerialExecutionStrategy.execute(AsyncSerialExecutionStrategy.java:36) ~[graphql-java-14.1.jar:na]
        at graphql.execution.Execution.executeOperation(Execution.java:165) ~[graphql-java-14.1.jar:na]
        at graphql.execution.Execution.execute(Execution.java:106) ~[graphql-java-14.1.jar:na]
        at graphql.GraphQL.execute(GraphQL.java:623) ~[graphql-java-14.1.jar:na]
        at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:556) ~[graphql-java-14.1.jar:na]
        at graphql.GraphQL.executeAsync(GraphQL.java:520) ~[graphql-java-14.1.jar:na]
        at graphql.kickstart.execution.GraphQLInvoker$$Lambda$492/212065138.executeAsync(Unknown Source) ~[na:na]
        at graphql.kickstart.execution.GraphQLInvoker.executeAsync(GraphQLInvoker.java:26) ~[graphql-java-kickstart-9.2.0.jar:na]
        at graphql.kickstart.execution.GraphQLInvoker.query(GraphQLInvoker.java:38) ~[graphql-java-kickstart-9.2.0.jar:na]
        at graphql.kickstart.execution.GraphQLInvoker.query(GraphQLInvoker.java:31) ~[graphql-java-kickstart-9.2.0.jar:na]
        at graphql.kickstart.servlet.HttpRequestHandlerImpl.invoke(HttpRequestHandlerImpl.java:67) [graphql-java-servlet-9.2.0.jar:na]
        at graphql.kickstart.servlet.HttpRequestHandlerImpl.execute(HttpRequestHandlerImpl.java:52) [graphql-java-servlet-9.2.0.jar:na]
        at graphql.kickstart.servlet.HttpRequestHandlerImpl.handle(HttpRequestHandlerImpl.java:37) [graphql-java-servlet-9.2.0.jar:na]
        at graphql.kickstart.servlet.AbstractGraphQLHttpServlet.doRequest(AbstractGraphQLHttpServlet.java:148) [graphql-java-servlet-9.2.0.jar:na]
        at graphql.kickstart.servlet.AbstractGraphQLHttpServlet.doRequestAsync(AbstractGraphQLHttpServlet.java:138) [graphql-java-servlet-9.2.0.jar:na]
        at graphql.kickstart.servlet.AbstractGraphQLHttpServlet.doPost(AbstractGraphQLHttpServlet.java:170) [graphql-java-servlet-9.2.0.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-embed-websocket-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92) [spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) [spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) [spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:93) [spring-boot-actuator-2.3.1.RELEASE.jar:2.3.1.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) [spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.7.RELEASE.jar:5.2.7.RELEASE]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_05]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_05]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.36.jar:9.0.36]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
Caused by: io.github.classgraph.ClassGraphException: Could not get value of field in object: nonapi.io.github.classgraph.scanspec.ScanSpec@41fde3ac
        at io.github.classgraph.ClassGraphException.newClassGraphException(ClassGraphException.java:89) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.toJSONGraph(JSONSerializer.java:397) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.convertVals(JSONSerializer.java:196) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.toJSONGraph(JSONSerializer.java:386) ~[classgraph-4.8.78.jar:4.8.78]
        ... 80 common frames omitted
Caused by: io.github.classgraph.ClassGraphException: Could not get value of field in object: file:/H:/MASTER_ING_WEB/CURSO_2019-20/TFM/Proyectos/Damas/
        at io.github.classgraph.ClassGraphException.newClassGraphException(ClassGraphException.java:89) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.toJSONGraph(JSONSerializer.java:397) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.convertVals(JSONSerializer.java:196) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.toJSONGraph(JSONSerializer.java:345) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.convertVals(JSONSerializer.java:196) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.toJSONGraph(JSONSerializer.java:386) ~[classgraph-4.8.78.jar:4.8.78]
        ... 82 common frames omitted
Caused by: java.lang.IllegalArgumentException: Class java.net.URLStreamHandlerFactory does not have an accessible default (no-arg) constructor
        at nonapi.io.github.classgraph.json.ClassFieldCache.getDefaultConstructorForConcreteTypeOf(ClassFieldCache.java:217) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.FieldTypeInfo.<init>(FieldTypeInfo.java:180) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.ClassFields.<init>(ClassFields.java:164) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.ClassFieldCache.get(ClassFieldCache.java:137) ~[classgraph-4.8.78.jar:4.8.78]
        at nonapi.io.github.classgraph.json.JSONSerializer.toJSONGraph(JSONSerializer.java:373) ~[classgraph-4.8.78.jar:4.8.78]

**Comment by GameEngineers** [comment]
The problem was solved. I change the overrideClasspath for overrideClassLoaders, and passing it URLClassLoader constructed with the URLs, and now is working nice.
Thanks.

**Comment by lukehutch** [comment]
You're not the first person who had done this, so I think the code needs to detect this problem and report an error. I'll add a check. Thanks for the report!
