### ISSUE TITLE
java.lang.NoSuchFieldException: allowedModes during ClassGraph initialization

### ISSUE THREAD

**Issue by jkroftPDI** [classgraph/classgraph#563]
This issue occurred on my linux machine (OpenSUSE Leap 15.2) using [IBM Semeru 8.0.302.0](https://developer.ibm.com/languages/java/semeru-runtimes/downloads) (formally __OpenJDK 8u302-b08__ with **Eclipse J9 0.27.0**). Here is the stack trace:
```
java.lang.ExceptionInInitializerError
	at java.lang.J9VMInternals.ensureError(J9VMInternals.java:145)
	at java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:134)
	at io.github.classgraph.ModulePathInfo.<init>(ModulePathInfo.java:136)
	at nonapi.io.github.classgraph.scanspec.ScanSpec.<init>(ScanSpec.java:231)
	at io.github.classgraph.ClassGraph.<init>(ClassGraph.java:67)
        ...
Caused by: io.github.toolfactory.jvm.Driver$InitializationException: Could not initiliaze DefaultDriver
	at io.github.toolfactory.jvm.DefaultDriver.throwException(DefaultDriver.java:324)
	at io.github.toolfactory.jvm.DefaultDriver.<init>(DefaultDriver.java:121)
	at nonapi.io.github.classgraph.utils.ReflectionUtils.<clinit>(ReflectionUtils.java:48)
	... 78 more
Caused by: io.github.toolfactory.jvm.ObjectProvider$BuildingException: Unable to build the related object of io.github.toolfactory.jvm.function.catalog.DefineHookClassFunction
	at io.github.toolfactory.jvm.ObjectProvider.getOrBuildObject(ObjectProvider.java:57)
	at io.github.toolfactory.jvm.DefaultDriver.initHookClassDefiner(DefaultDriver.java:304)
	at io.github.toolfactory.jvm.DefaultDriver.<init>(DefaultDriver.java:103)
	... 79 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.github.toolfactory.jvm.ObjectProvider.getOrBuildObject(ObjectProvider.java:51)
	... 81 more
Caused by: io.github.toolfactory.jvm.ObjectProvider$BuildingException: Unable to build the related object of io.github.toolfactory.jvm.function.catalog.ConsulterSupplier
	at io.github.toolfactory.jvm.ObjectProvider.getOrBuildObject(ObjectProvider.java:57)
	at io.github.toolfactory.jvm.function.catalog.DefineHookClassFunction$ForJava7.<init>(DefineHookClassFunction.java:62)
	... 86 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at io.github.toolfactory.jvm.ObjectProvider.getOrBuildObject(ObjectProvider.java:51)
	... 87 more
Caused by: java.lang.NoSuchFieldException: allowedModes
	at java.lang.Class.getDeclaredFieldImpl(Native Method)
	at java.lang.Class.getDeclaredFieldInternal(Class.java:846)
	at java.lang.Class.getDeclaredField(Class.java:821)
	at io.github.toolfactory.jvm.function.catalog.ConsulterSupplier$ForJava7.<init>(ConsulterSupplier.java:53)
	... 92 more
```

**Comment by lukehutch** [comment]
Thanks for the report. This is due to a new [reflection mechanism](https://github.com/toolfactory/jvm-driver) used by ClassGraph to access the private classpath of classloaders. I will roll back this change for now.

**Comment by lukehutch** [comment]
The change is rolled back as of release 4.8.118 -- apologies for the problem!

**Comment by lukehutch** [comment]
Actually, please try 4.8.120, not 4.8.118.

**Comment by jkroftPDI** [comment]
It seems the problem is inside the `jvm-driver` (I've tried 6.2.2, 4.x, 3.x) and the behaviour is absolutely same. So I guess the rollback of changes won't help much.

**Comment by lukehutch** [comment]
Thanks, yes. IBM Semeru renamed an internal field. JVM-Driver needs to accept either field name. The author is working on that.

For now, I made ClassGraph optionally depend upon a different project, Narcissus. The problem should be solved. Please see the release notes for ClassGraph-4.8.120.

**Comment by jkroftPDI** [comment]
Thank you for the information.
