### ISSUE TITLE
Failed to build-time scan on graalvm native image

### ISSUE THREAD

**Issue by lost22git** [classgraph/classgraph#681]
the example from `https://github.com/SoftInstigate/classgraph-on-graalvm`  does not apply

```
[1/7] Initializing...                                                                                    (3.4s @ 0.18GB)
 Version info: 'GraalVM 22.1.0 Java 17 CE'
 C compiler: cl.exe (microsoft, x64, 19.29.30133)
 Garbage collector: Serial GC
[2/7] Performing analysis...  [*]                                                                        (5.1s @ 0.79GB)
   3,414 (76.94%) of  4,437 classes reachable
   4,295 (51.79%) of  8,293 fields reachable
  15,361 (45.62%) of 33,669 methods reachable
     119 classes,    44 fields, and   277 methods registered for reflection

Error: java.util.concurrent.ExecutionException: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: type is not available in this platform: com.oracle.svm.hosted.NativeImageSystemClassLoader
com.oracle.graal.pointsto.util.AnalysisError: java.util.concurrent.ExecutionException: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: type is not available in this platform: com.oracle.svm.hosted.NativeImageSystemClassLoader
        at com.oracle.graal.pointsto.util.AnalysisError.shouldNotReachHere(AnalysisError.java:172)
        at com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:66)
        at com.oracle.graal.pointsto.heap.ImageHeapScanner.lambda$postTask$9(ImageHeapScanner.java:611)
        at com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.util.concurrent.ExecutionException: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: type is not available in this platform: com.oracle.svm.hosted.NativeImageSystemClassLoader
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:64)
```

**Comment by lukehutch** [comment]
Hi, nothing in that stacktrace involves ClassGraph code, so I don't know what to advise. However I believe that GraalVM code is first compiled into bytecodes, then converted into native code by the partial evaluator. You want to do your build-time scan between those two stages, and you don't want to include the scanner code in the bytecodes that are passed to the second stage. Unfortunately I have no idea exactly how to do that, so I would need your help to come up with a solution.

**Comment by lukehutch** [comment]
Closing due to lack of response -- please comment if you are able to help figure out how to get this working. (I don't use GraalVM so I don't know what to suggest.)
