### ISSUE TITLE
Support GraalVM native images

### ISSUE THREAD

**Issue by mmoayyed** [classgraph/classgraph#750]
When building a "native" application with classgraph `4.8.154`, using GraalVM `22.3` and `JDK 17`, the final generated image fails to run with the following:

```
Exception in thread "main" java.lang.IllegalArgumentException: Method "getLayer" could not be invoked: java.lang.NoSuchMethodException: Could not find method java.lang.Module.getLayer
	at nonapi.io.github.classgraph.reflection.ReflectionUtils.invokeMethod(ReflectionUtils.java:231)
	at nonapi.io.github.classgraph.classpath.ModuleFinder.findModuleRefsFromCallstack(ModuleFinder.java:227)
	at nonapi.io.github.classgraph.classpath.ModuleFinder.<init>(ModuleFinder.java:284)
	at nonapi.io.github.classgraph.classpath.ClasspathFinder.<init>(ClasspathFinder.java:164)
	at io.github.classgraph.Scanner.<init>(Scanner.java:166)
	at io.github.classgraph.ClassGraph.scanAsync(ClassGraph.java:1531)
	at io.github.classgraph.ClassGraph.scanAsync(ClassGraph.java:1559)
	at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1584)
	at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1623)
```

...and...

```
Caused by: java.lang.RuntimeException: Could not find canHandle method for nonapi.io.github.classgraph.classloaderhandler.AntClassLoaderHandler
	at nonapi.io.github.classgraph.classloaderhandler.ClassLoaderHandlerRegistry$ClassLoaderHandlerRegistryEntry.<init>(ClassLoaderHandlerRegistry.java:163)
	at nonapi.io.github.classgraph.classloaderhandler.ClassLoaderHandlerRegistry$ClassLoaderHandlerRegistryEntry.<init>(ClassLoaderHandlerRegistry.java:134)
	at nonapi.io.github.classgraph.classloaderhandler.ClassLoaderHandlerRegistry.<clinit>(ClassLoaderHandlerRegistry.java:47)
	... 14 more
Caused by: java.lang.NoSuchMethodException: nonapi.io.github.classgraph.classloaderhandler.AntClassLoaderHandler.canHandle(java.lang.Class, nonapi.io.github.classgraph.utils.LogNode)
	at java.base@17.0.5/java.lang.Class.getDeclaredMethod(DynamicHub.java:2675)
	at nonapi.io.github.classgraph.classloaderhandler.ClassLoaderHandlerRegistry$ClassLoaderHandlerRegistryEntry.<init>(ClassLoaderHandlerRegistry.java:159)
	... 16 more
```

In a Spring Boot/Spring world, fixing these would require something akin to the following:

```java
public class MyRuntimeHints implements RuntimeHintsRegistrar {
    public MyRuntimeHints() {
    }

    @Override
    public void registerHints(final RuntimeHints hints, final ClassLoader classLoader) {
        hints.reflection().registerType(java.lang.Module.class, MemberCategory.INVOKE_DECLARED_METHODS);
    }
}
```

...which in the end generates AOT JSON metadata for reflection as such:

```json
  {
    "name": "java.lang.Module",
    "allDeclaredMethods": true
  }
```

...and this would have to be repeated for `AntClassLoaderHandler`, and likely many others. 

This JSON metadata is ideally found and provided by the project itself, so the AOT engine can just pick up up what it needs without having each consumer project declare and configure reflection metadata on their own. Alternatively, there is https://github.com/oracle/graalvm-reachability-metadata which allows contributors to push this sort of configuration into a global repository that may be used by AOT engines and appropriate build plugins. 

Before reaching out to graalvm-reachability-metadata, I figured to ask: Is this something classgraph might be open to supporting out of the box, whereby native-image configuration would be maintained and hosted here directly and then released?

**Comment by mmoayyed** [comment]
Forgot to add that I am happy to help and assist however I can to move this effort along, should you be open to supporting it. I realize this is extra work, and likely something you may wish to punt, which is perfectly OK. Thank you!

**Comment by lukehutch** [comment]
Hi, GraalVM native images do not have a concept of a classpath at runtime (just like Android, for similar reasons -- both are cross-compiled to a non-JVM runtime environment, and Graal additionally runs partial evaluation). There is really no way for ClassGraph to support runtime scanning in environments like this.

However, there are some build-time scanning instructions here: https://github.com/classgraph/classgraph/wiki/Build-Time-Scanning

They may need updating. Please experiment with this to find the best solution for GraalVM, and let me know if you want to help improve these docs.

**Comment by lukehutch** [comment]
PS this is linked from the above wiki URL. https://github.com/SoftInstigate/classgraph-on-graalvm

**Comment by mmoayyed** [comment]
Thank you! Will do.

**Comment by lukehutch** [comment]
Any updates?
