### ISSUE TITLE
Calling `ScanResult.close()` and `ClassGraph.scan()` from two threads using `4.8.155` can result in a `RuntimeException`

### ISSUE THREAD

**Issue by erdi** [classgraph/classgraph#757]
When that happens the stacktrace looks as follows:
```
Caused by: java.lang.RuntimeException: Cannot use reflection after ScanResult has been closed
	at nonapi.io.github.classgraph.reflection.ReflectionUtils.invokeMethod(ReflectionUtils.java:241)
	at io.github.classgraph.ModuleRef.<init>(ModuleRef.java:91)
	at nonapi.io.github.classgraph.classpath.ModuleFinder.findModuleRefs(ModuleFinder.java:189)
	at nonapi.io.github.classgraph.classpath.ModuleFinder.findModuleRefsFromCallstack(ModuleFinder.java:258)
	at nonapi.io.github.classgraph.classpath.ModuleFinder.<init>(ModuleFinder.java:284)
	at nonapi.io.github.classgraph.classpath.ClasspathFinder.<init>(ClasspathFinder.java:168)
	at io.github.classgraph.Scanner.<init>(Scanner.java:166)
	at io.github.classgraph.ClassGraph.scanAsync(ClassGraph.java:1531)
	at io.github.classgraph.ClassGraph.scanAsync(ClassGraph.java:1559)
	at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1584)
	at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1623)
	at io.github.classgraph.ClassGraph.scan(ClassGraph.java:1636)
```	

I believe that this is down to [the new call to static `ReflectionUtils.unloadReflectionDriver()` from `ScanResult.close()`](https://github.com/classgraph/classgraph/commit/955baf59b9788d50f1854f120bd937eff0b9409e#diff-ca7988d4cc5346f9d77b470beda2e1f9021f8823de01c99d349c42c1ef8141d0R1599) added in https://github.com/classgraph/classgraph/commit/955baf59b9788d50f1854f120bd937eff0b9409e.

Hopefully this is obvious enough not to need a reproducer. I'm happy to answer any questions as necessary to help in tracking this down.

**Comment by lukehutch** [comment]
Thanks for reporting the problem and tracking down the cause. I fixed this and released 4.8.156. Please confirm whether this solves the problem for you.

**Comment by erdi** [comment]
Wow, impressive turnaround, @lukehutch, thanks. I will make sure to report back if we find any issues with the fix and also file new issues if I happen to find other bugs in the future.

**Comment by lukehutch** [comment]
You're welcome, I try to turn around critical bugfixes in 24 hours. It was a large change, so I hope it doesn't break anything else for you or others! At least all the tests pass...
