### ISSUE TITLE
Narcissus failing on macOS

### ISSUE THREAD

**Issue by lukehutch** [classgraph/classgraph#890]
Need to figure out why Narcissus is failing on macOS:

```
[INFO] Running io.github.classgraph.features.EncapsulationCircumventionTest
Error:  Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.067 s <<< FAILURE! -- in io.github.classgraph.features.EncapsulationCircumventionTest
Error:  io.github.classgraph.features.EncapsulationCircumventionTest.testNarcissus -- Time elapsed: 0.020 s <<< FAILURE!
org.opentest4j.AssertionFailedError: 

expected: "NarcissusReflectionDriver"
 but was: "StandardReflectionDriver"
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at io.github.classgraph.features.EncapsulationCircumventionTest.testNarcissus(EncapsulationCircumventionTest.java:30)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
```

**Comment by michael-simons** [comment]
This happens because Narcissus is only Intel macOS, not Arm64, I guess…
